-- Validação simples da carga

SELECT COUNT(*) FROM IFOOD_CUSTOMERS;

-- Query usada como ponto de partida pro DataFrame de Machine Learning
SELECT
    ID, YEAR_BIRTH, EDUCATION, MARITAL_STATUS, INCOME, KIDHOME, TEENHOME,
    DT_CUSTOMER, RECENCY, MNT_WINES, MNT_FRUITS, MNT_MEAT_PRODUCTS,
    MNT_FISH_PRODUCTS, MNT_SWEET_PRODUCTS, MNT_GOLD_PRODS,
    NUM_DEALS_PURCHASES, NUM_WEB_PURCHASES, NUM_CATALOG_PURCHASES,
    NUM_STORE_PURCHASES, NUM_WEB_VISITS_MONTH,
    ACCEPTED_CMP3, ACCEPTED_CMP4, ACCEPTED_CMP5, ACCEPTED_CMP1, ACCEPTED_CMP2,
    COMPLAIN, RESPONSE
FROM IFOOD_CUSTOMERS;
